### ISSUE TITLE
TODO/FUTURE UPDATE: Modular gun sprite update.

### ISSUE THREAD

**Issue by EvilJackCarver** [Eclipse-Station/Eclipse-Station-13#203]
This issue is to track the framework and todos regarding the upcoming modular gun sprite update.

# Overview
The update aims to make spriting future **semiautomatic** handguns easier and more lightweight, using the overlay system. 

# Planned features and conventions
* Different icon states for the gun base, the grips, slide, magazine, and accessories such as a flashlight or frame-mounted sight.
* Singular weapon identifier, to make weapon icon updating more streamlined with less code rewrites.
* Planned conventions:
  * Base icon: [id]-base
  * Slide icon: [id]-slide-[finish]
  * Grip icon: [id]-grip-[style]
  * Magazine icon: [id]-magazine-[style]
  * Accessory icon: [id]-accessory-[style]
* Ability to change styles on the fly

# Todo
- [x] Create base modular defines
- [x] Create examples
- [x] Create documentation
- [x] Create a centralised icon file, or icon files for the various weapons (centralised would be more ideal)
- [x] Add in FN FNX and make available to players somehow
- [x] Add in CZ 97B and make available to players somehow
- [x] Add in ability to change weapon styles on the fly

**Comment by EvilJackCarver** [comment]
Most of the code is implemented, initial commits are pushed to https://github.com/EvilJackCarver/AEIOUStation13/tree/modular-gun-sprite-update

Still need some work on the implementation, and reskin mechanics (currently only the FNX is able to do so). 

Completely untested, as of yet.

**Comment by EvilJackCarver** [comment]
>tfw didn't close the right one with the PR
